### ISSUE TITLE
Feature Request: 增加 api 版本调用功能

### ISSUE THREAD

**Issue by bolechen** [overtrue/laravel-youzan#8]
有赞官方 api 版本目前处在 3.0.0 和 4.0.0 切换中间，部分 api 已经有了 4.0.0 版本，比如订单接口是目前用的最多的

https://www.youzanyun.com/docs/guide/3401/4212

> youzan.trade.get

官方建议

> 请使用4.0.0版本(3.0版本已不维护) ，4.0.0版本接口性能更好，返回数据结构更清晰。

目前的版本调用只能统一在 config 中设置，能否公开一个方法，可以在调用前自由设置 api 版本，感谢！

**Comment by overtrue** [comment]
你觉得这样子 OK 不？

```php
app('youzan')->post('youzan.shop.create', ['name' => 'Test store']); // 3.0.0

// 对当前请求设置版本
app('youzan')->version(4)->post('youzan.shop.create', ['name' => 'Test store']); // 4.0.0

// 下面的请求还是会被重置
app('youzan')->post('youzan.shop.create', ['name' => 'Test store']); // 3.0.0
```

**Comment by bolechen** [comment]
> 你觉得这样子 OK 不？
> 
> ```
> app('youzan')->post('youzan.shop.create', ['name' => 'Test store']); // 3.0.0
> 
> // 对当前请求设置版本
> app('youzan')->version(4)->post('youzan.shop.create', ['name' => 'Test store']); // 4.0.0
> 
> // 下面的请求还是会被重置
> app('youzan')->post('youzan.shop.create', ['name' => 'Test store']); // 3.0.0
> ```

可以，太棒了

**Comment by overtrue** [comment]
那就等我实现吧，手里工作略忙。

**Comment by overtrue** [comment]
当前项目不再新增功能，仅做安全性更新。
